name = "local-ip-geo"
main = "src/index.ts"
compatibility_date = "2022-11-30"
compatibility_flags = []
workers_dev = true
route = { pattern = "local-ip-geo.demosjarco.dev", custom_domain = true }
usage_model = "bundled"
minify = true